<a href="https://colab.research.google.com/github/0507che/0724/blob/main/0725.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('HI')

HI


In [ ]:
pip list

Package                            Version
---------------------------------- --------------------
alabaster                          0.7.12
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.

In [ ]:
pwd

'C:\\Users\\TKU-STAFF'

In [ ]:
pip install wget

  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9672 sha256=30bb0d75e87cfab33fc8ca88a81679dd307b1ebd1517334a76883ab32b926cb0
  Stored in directory: c:\users\tku-staff\appdata\local\pip\cache\wheels\04\5f\3e\46cc37c5d698415694d83f607f833f83f0149e49b3af9d0f38
Successfully built wget
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip list

Package                            Version
---------------------------------- --------------------
alabaster                          0.7.12
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.

In [ ]:
import wget

In [ ]:
wget.download('https://github.com/tku-peiyucheng/TKU-DM-Class/blob/main/scores.csv')

'scores (1).csv'

In [ ]:
ls

 磁碟區 C 中的磁碟沒有標籤。
 磁碟區序號:  2F21-0399

 C:\Users\TKU-STAFF 的目錄

2023/07/25  下午 04:19    <DIR>          .
2023/07/25  下午 04:19    <DIR>          ..
2021/02/18  下午 03:07    <DIR>          .anaconda
2023/07/25  下午 04:19    <DIR>          .conda
2022/02/15  上午 10:38                43 .condarc
2022/02/15  上午 10:42    <DIR>          .continuum
2023/07/25  下午 03:52    <DIR>          .ipynb_checkpoints
2023/07/25  下午 03:51    <DIR>          .ipython
2021/03/20  上午 08:17    <DIR>          .VirtualBox
2023/07/25  下午 04:17            39,705 0725.ipynb
2020/08/19  上午 08:41    <DIR>          3D Objects
2022/02/15  上午 10:42    <DIR>          anaconda3
2020/08/19  上午 08:41    <DIR>          Contacts
2022/10/06  上午 08:16    <DIR>          Desktop
2022/10/06  上午 08:16    <DIR>          Documents
2023/07/25  下午 03:47    <DIR>          Downloads
2020/08/19  上午 08:41    <DIR>          Favorites
2020/08/17  上午 11:20    <DIR>          Intel
2020/08/19  上午 08:41    <DIR>          Links
2020/08/19  上午 08:41    

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

In [ ]:
na=np.genfromtxt('scores.csv',delimiter=',',skip_header=1)
print(na.shape)

(30, 4)


In [ ]:
print(na)

[[ 1. 87. 85. 82.]
 [ 2. 92. 87. 90.]
 [ 3. 80. 91. 87.]
 [ 4. 78. 82. 95.]
 [ 5. 88. 89. 90.]
 [ 6. 82. 87. 88.]
 [ 7. 90. 92. 82.]
 [ 8. 87. 80. 90.]
 [ 9. 95. 78. 87.]
 [10. 90. 88. 95.]
 [11. 88. 89. 75.]
 [12. 82. 91. 66.]
 [13. 90. 82. 87.]
 [14. 87. 89. 92.]
 [15. 95. 87. 80.]
 [16. 90. 92. 78.]
 [17. 82. 80. 88.]
 [18. 90. 78. 93.]
 [19. 67. 87. 95.]
 [20. 91. 82. 88.]
 [21. 82. 81. 82.]
 [22. 79. 87. 90.]
 [23. 87. 92. 87.]
 [24. 92. 82. 95.]
 [25. 80. 90. 78.]
 [26. 78. 76. 91.]
 [27. 66. 90. 82.]
 [28. 89. 77. 89.]
 [29. 87. 95. 87.]
 [30. 73. 90. 92.]]
